### ISSUE TITLE
brand patterns toolkit; ie8 styles

### ISSUE THREAD

**Issue by osteffich** [wvuweb/cleanslate-toolkit#10]
I founds some issues with the cleanslate toolkit patterns working in ie8:

1. in the default.html file, there is a typo regarding conditional stylesheets. 

It currently reads:
```html    
<!--[if IE 9]>
  <r:include_stylesheet name="ie9" />
<![endif]-->
<!--[if lt IE9]>
  <r:include_stylesheet name="ie8" />
<![endif]--> 
```
and throws an error in ie8 at the top of the browser window.

2. the search bar region on the college level masthead is bumping down to the second line full screen view in ie8. The other times I've cloned the main brand-patterns folder and adapted it to my site without using the cleanslate toolkit I have not had this issue.

*Edit*
I'm not sure how the default file *should* read, but I've found that only listing 
```html
    <!--[if lt IE 9]>
      <r:include_stylesheet name="ie8" />
    <![endif]-->
```
resolves the above issues.

**Comment by adamjohnson** [comment]
Looks like this is a https://github.com/wvuweb/brand-patterns issue, not a CleanSlate Toolkit issue.

Furthermore, it looks like Adam Glenn resolved this in https://github.com/wvuweb/brand-patterns/commit/aeea002bf51c610f44e1c6a396800d926f866555 .
