### ISSUE TITLE
Captions for blog photos using title

### ISSUE THREAD

**Issue by HalleyK** [wvuweb/cleanslate-toolkit#11]
Would it be possible to format the media title to show up under the image as a caption (smaller, lighter, and italicized text) in the blog article template without the author having to access the HTML?

**Comment by adamjohnson** [comment]
Don't think so. But you could have the author input a class on the media they're inserting using the GUI and use [one of these selectors](https://css-tricks.com/child-and-sibling-selectors/) to format the tag below it.

Also, these types of requests should be posted on the [wvuweb/cleanslate-cms](https://github.com/wvuweb/cleanslate-cms/issues) issue tracker as it's more of a CleanSlate functionality question than an issue/bug with the CleanSlate toolkit.
